#!/usr/bin/env python3
"""Check that every URL in the published documents resolves (2xx or 3xx).

Run from the repository root: python3 ci/check_links.py
Needs curl on PATH. Transient 5xx/429 responses (the runner network
occasionally throttles github.com) are retried with a short wait.
"""

import os
import re
import subprocess
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _textfiles import text_files  # noqa: E402

URL = re.compile(r"https?://[^\s\)\]\"'<>`]+")
ALLOW = {
    # Generated by this repository after the PR that adds it is merged.
    "https://raw.githubusercontent.com/Ovallus/solstitium-evidence/main/freshness.json":
        "generated file; exists on main once this change is merged",
}


def urls():
    found = {}
    for path in sorted(text_files()):
        try:
            text = open(path, encoding="utf-8").read()
        except (UnicodeDecodeError, OSError):
            continue
        for m in URL.finditer(text):
            u = m.group(0).rstrip(".,;:")
            found.setdefault(u, path)
    return found


def probe(url, attempts=3):
    last = ("", "")
    for i in range(attempts):
        r = subprocess.run(
            ["curl", "-sS", "-o", "/dev/null", "-L", "--max-time", "25",
             "-A", "solstitium-evidence-link-check", "-w", "%{http_code}", url],
            capture_output=True, text=True)
        code, err = r.stdout.strip(), r.stderr.strip()
        last = (code, err)
        retryable = (not code.isdigit()) or int(code) >= 500 or code == "429"
        if not retryable or i == attempts - 1:
            return last
        time.sleep(4 + 6 * i)
    return last


def main():
    fails = []
    for url, where in sorted(urls().items()):
        if url in ALLOW:
            print(f"skip  {url}  ({ALLOW[url]})")
            continue
        code, err = probe(url)
        ok = code.isdigit() and 200 <= int(code) < 400
        print(f"{'ok   ' if ok else 'FAIL '} {code or '???'}  {url}")
        if not ok:
            fails.append((url, where, code, err[:120]))
    if fails:
        print("\nfailed links:")
        for url, where, code, err in fails:
            print(f"  {url} (in {where}): {code} {err}")
        print("\nIf a page is temporarily unreachable, re-run; if it moved, fix "
              "the document.")
        return 1
    print("links OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
