#!/usr/bin/env python3
"""Check that every URL in the published documents resolves (2xx or 3xx).

Run from the repository root: python3 ci/check_links.py
Needs curl on PATH.
"""

import os
import re
import subprocess
import sys

URL = re.compile(r"https?://[^\s\)\]\"'<>`]+")
EXCLUDE_DIRS = {".git"}
TEXT_EXT = {".md", ".txt", ".json", ".cff", ".yml", ".yaml"}
SPECIAL = {"LICENSE"}
ALLOW = {
    # Generated by this repository after the PR that adds it is merged.
    "https://raw.githubusercontent.com/Ovallus/solstitium-evidence/main/freshness.json":
        "generated file; exists on main once this change is merged",
}


def content_files():
    for base, dirs, names in os.walk("."):
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
        for name in names:
            ext = os.path.splitext(name)[1].lower()
            if ext in TEXT_EXT or name in SPECIAL:
                yield os.path.join(base, name)


def urls():
    found = {}
    for path in sorted(content_files()):
        try:
            text = open(path, encoding="utf-8").read()
        except (UnicodeDecodeError, OSError):
            continue
        for m in URL.finditer(text):
            u = m.group(0).rstrip(".,;:")
            found.setdefault(u, path)
    return found


def probe(url):
    r = subprocess.run(
        ["curl", "-sS", "-o", "/dev/null", "-L", "--max-time", "25",
         "-A", "solstitium-evidence-link-check", "-w", "%{http_code}", url],
        capture_output=True, text=True)
    return r.stdout.strip(), r.stderr.strip()


def main():
    fails = []
    for url, where in sorted(urls().items()):
        if url in ALLOW:
            print(f"skip  {url}  ({ALLOW[url]})")
            continue
        code, err = probe(url)
        ok = code.isdigit() and 200 <= int(code) < 400
        print(f"{'ok   ' if ok else 'FAIL '} {code or '???'}  {url}")
        if not ok:
            fails.append((url, where, code, err[:120]))
    if fails:
        print("\nfailed links:")
        for url, where, code, err in fails:
            print(f"  {url} (in {where}): {code} {err}")
        print("\nIf a page is temporarily unreachable, re-run; if it moved, fix "
              "the document.")
        return 1
    print("links OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
