#!/usr/bin/env python3
"""Check that every URL in the published documents resolves.

Run from the repository root: python3 ci/check_links.py
Needs curl on PATH.

GitHub repository/file links are verified through the GitHub API first (the
HTML pages are intermittently throttled from CI runner networks with 503s);
curl is the fallback there and the primary path for every other host.
Transient 5xx/429 responses are retried: curl-level retries up to about two
minutes per URL, then one outer re-attempt. Scans the published documents
only; tooling directories (ci/, .github/) embed URL patterns as code.

Set GH_TOKEN (the workflow passes github.token) to lift API rate limits.
"""

import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _textfiles import text_files  # noqa: E402

URL = re.compile(r"https?://[^\s\)\]\"'<>`]+")
REPO_RE = re.compile(r"^https://github\.com/([^/]+)/([^/]+?)(?:\.git)?/?$")
BLOB_RE = re.compile(r"^https://github\.com/([^/]+)/([^/]+)/blob/([^/]+)/(.+)$")
ISSUES_RE = re.compile(r"^https://github\.com/([^/]+)/([^/]+)/issues/?$")
ALLOW = {
    # Generated by this repository after the PR that adds it is merged.
    "https://raw.githubusercontent.com/Ovallus/solstitium-evidence/main/freshness.json":
        "generated file; exists on main once this change is merged",
}


def urls():
    found = {}
    # Published documents only: tooling sources (ci/, .github/) embed URL
    # patterns as code, not as clickable links.
    for path in sorted(text_files(exclude_dirs={"ci", ".github"})):
        try:
            text = open(path, encoding="utf-8").read()
        except (UnicodeDecodeError, OSError):
            continue
        for m in URL.finditer(text):
            u = m.group(0).rstrip(".,;:")
            found.setdefault(u, path)
    return found


def gh_api_check(url, token):
    """Return (handled, ok, note). handled=False means: use curl instead."""
    api = None
    m = BLOB_RE.match(url)
    if m:
        owner, repo, ref, path = m.groups()
        api = (f"https://api.github.com/repos/{owner}/{repo}/contents/"
               f"{path}?ref={ref}")
    else:
        m = REPO_RE.match(url) or ISSUES_RE.match(url)
        if m:
            owner, repo = m.group(1), m.group(2)
            api = f"https://api.github.com/repos/{owner}/{repo}"
    if not api:
        return False, False, "not a github api url"
    req = urllib.request.Request(api, headers={
        "User-Agent": "solstitium-evidence-link-check",
        "Accept": "application/vnd.github+json",
    })
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return True, 200 <= r.status < 300, f"api {r.status}"
    except urllib.error.HTTPError as e:
        if e.code in (403, 429):
            return False, False, f"api {e.code} (falling back to curl)"
        return True, False, f"api {e.code}"
    except Exception as e:
        return False, False, f"api error {e}"[:120]


def curl_probe(url, attempts=2):
    last = ("", "")
    for i in range(attempts):
        r = subprocess.run(
            ["curl", "-sS", "-o", "/dev/null", "-L",
             "--max-time", "40",
             "--retry", "8", "--retry-delay", "6", "--retry-max-time", "120",
             "-A", "solstitium-evidence-link-check", "-w", "%{http_code}", url],
            capture_output=True, text=True)
        code = r.stdout.strip()
        err = f"rc={r.returncode} {r.stderr.strip()}".strip()[:160]
        last = (code, err)
        retryable = (not code.isdigit()) or int(code) >= 500 or code == "429"
        if not retryable or i == attempts - 1:
            return last
        time.sleep(15)
    return last


def main():
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN") or ""
    fails = []
    for url, where in sorted(urls().items()):
        if url in ALLOW:
            print(f"skip  {url}  ({ALLOW[url]})")
            continue
        handled, ok, note = gh_api_check(url, token)
        if handled:
            code, err = note, ""
        else:
            code, err = curl_probe(url)
            ok = code.isdigit() and 200 <= int(code) < 400
        print(f"{'ok   ' if ok else 'FAIL '} {code or '???'}  {url}")
        if not ok:
            fails.append((url, where, code, err))
        time.sleep(1)
    if fails:
        print("\nfailed links:")
        for url, where, code, err in fails:
            print(f"  {url} (in {where}): {code} {err}")
        print("\nIf a page is temporarily unreachable, re-run; if it moved, fix "
              "the document.")
        return 1
    print("links OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
